# Generated by Django 3.2.9 on 2021-12-06 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('reduction', models.FloatField(default=0)),
                ('event', models.JSONField(blank=True, null=True)),
                ('user_count', models.IntegerField(default=0)),
                ('total_issuing_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('point', models.FloatField(default=0)),
                ('op', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OriginalPoint.originalpoint')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('user', 'op'), name='lesson_unique'),
        ),
    ]
