# Generated by Django 3.2.9 on 2021-12-23 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OriginalPoint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalpoint',
            name='detailed_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='originalpoint',
            name='introduction',
            field=models.TextField(default=1, max_length=800),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='originalpoint',
            name='name',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', '半角英字のみ使用可能です(例:〇DEJIPO11×DEJIPO22)'), django.core.validators.MinLengthValidator(3)]),
        ),
    ]
