# Generated by Django 3.2.9 on 2021-12-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OriginalPoint', '0002_auto_20211224_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='total_get_point',
            field=models.FloatField(default=0),
        ),
    ]
