# Generated by Django 3.2.9 on 2022-01-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OriginalPoint', '0003_wallet_total_get_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalpoint',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
