# Generated by Django 3.2.9 on 2022-01-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OriginalPoint', '0004_originalpoint_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='originalpoint',
            old_name='reduction',
            new_name='pay_back_rate',
        ),
    ]
