# Generated by Django 3.2.9 on 2022-01-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OriginalPoint', '0005_rename_reduction_originalpoint_pay_back_rate'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wallet',
            name='lesson_unique',
        ),
        migrations.AddField(
            model_name='originalpoint',
            name='publishing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('user', 'op'), name='wallet_unique'),
        ),
    ]
