# Generated by Django 3.2.9 on 2022-01-21 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OriginalPoint', '0006_auto_20220121_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpEntryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('op', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OriginalPoint.originalpoint')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='opentryuser',
            constraint=models.UniqueConstraint(fields=('user', 'op'), name='op_entry_user_unique'),
        ),
    ]
