# Generated by Django 3.2.9 on 2022-01-26 02:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OriginalPoint', '0007_auto_20220121_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalpoint',
            name='name',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', '半角英字のみ使用可能です'), django.core.validators.MinLengthValidator(3)]),
        ),
    ]
