# Generated by Django 3.2.9 on 2021-12-06 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OriginalPoint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.IntegerField(choices=[(1, 'Admin'), (2, 'staff')], default=1)),
                ('op', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OriginalPoint.originalpoint')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
