# Generated by Django 3.2.9 on 2022-01-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opmanagement',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
