# Generated by Django 3.2.9 on 2022-01-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_opmanagement_is_active'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='opmanagement',
            constraint=models.UniqueConstraint(fields=('user', 'op'), name='op_manage_unique'),
        ),
    ]
