# Generated by Django 3.2.9 on 2022-01-26 02:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('OriginalPoint', '0008_alter_originalpoint_name'),
        ('Management', '0003_opmanagement_op_manage_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('use_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_limit', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('op', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OriginalPoint.originalpoint')),
            ],
        ),
    ]
