# Generated by Django 3.2.9 on 2022-01-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_opinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinvitation',
            name='use_limit_c',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opinvitation',
            name='using_c',
            field=models.IntegerField(default=0),
        ),
    ]
