# Generated by Django 3.2.9 on 2022-01-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0005_auto_20220126_1213'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='opinvitation',
            constraint=models.UniqueConstraint(fields=('op',), name='op_invite_ation_unique'),
        ),
    ]
